// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoutienScolaireV1.Azure.Models;

#nullable disable

namespace SoutienScolaireV1.Azure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("SoutienScolaireV1.Azure.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://robohash.org/consequunturaperiamet.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "rhackwell0@biglobe.ne.jp",
                            FirstName = "Rowland",
                            LastName = "Hackwell"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://robohash.org/ipsamsitlabore.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "mgellion1@amazon.com",
                            FirstName = "Marylinda",
                            LastName = "Gellion"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "https://robohash.org/autexenim.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "mhannant2@bbb.org",
                            FirstName = "Marleen",
                            LastName = "Hannant"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "https://robohash.org/facerevelitnihil.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "idrewet3@symantec.com",
                            FirstName = "Irene",
                            LastName = "Drewet"
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "https://robohash.org/quiquiaofficiis.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "hlindsay4@arizona.edu",
                            FirstName = "Henrietta",
                            LastName = "Lindsay"
                        },
                        new
                        {
                            Id = 6,
                            Avatar = "https://robohash.org/etquicorrupti.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "icamell5@gov.uk",
                            FirstName = "Ivor",
                            LastName = "Camell"
                        },
                        new
                        {
                            Id = 7,
                            Avatar = "https://robohash.org/dignissimossimiliqueillum.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "sbernth6@dmoz.org",
                            FirstName = "Sianna",
                            LastName = "Bernth"
                        },
                        new
                        {
                            Id = 8,
                            Avatar = "https://robohash.org/aperiamrerumrepudiandae.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "pmoneypenny7@wordpress.com",
                            FirstName = "Puff",
                            LastName = "Moneypenny"
                        },
                        new
                        {
                            Id = 9,
                            Avatar = "https://robohash.org/dignissimosauteligendi.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "agilstin8@ted.com",
                            FirstName = "Angie",
                            LastName = "Gilstin"
                        },
                        new
                        {
                            Id = 10,
                            Avatar = "https://robohash.org/quononoccaecati.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "vbergin9@studiopress.com",
                            FirstName = "Valentine",
                            LastName = "Bergin"
                        },
                        new
                        {
                            Id = 11,
                            Avatar = "https://robohash.org/utquisbeatae.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "ltayspella@auda.org.au",
                            FirstName = "Lorraine",
                            LastName = "Tayspell"
                        },
                        new
                        {
                            Id = 12,
                            Avatar = "https://robohash.org/rerumfacilismolestiae.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "aabramamovb@un.org",
                            FirstName = "Annabela",
                            LastName = "Abramamov"
                        },
                        new
                        {
                            Id = 13,
                            Avatar = "https://robohash.org/exercitationemerrornulla.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "sopferc@prweb.com",
                            FirstName = "Sharona",
                            LastName = "Opfer"
                        },
                        new
                        {
                            Id = 14,
                            Avatar = "https://robohash.org/nonoptiosit.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "hrooted@xing.com",
                            FirstName = "Humbert",
                            LastName = "Roote"
                        },
                        new
                        {
                            Id = 15,
                            Avatar = "https://robohash.org/quibusdametut.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "hkingsnode@msn.com",
                            FirstName = "Hardy",
                            LastName = "Kingsnod"
                        },
                        new
                        {
                            Id = 16,
                            Avatar = "https://robohash.org/nesciuntdelenitiut.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "gwetherheadf@quantcast.com",
                            FirstName = "Grace",
                            LastName = "Wetherhead"
                        },
                        new
                        {
                            Id = 17,
                            Avatar = "https://robohash.org/temporibusvoluptatumducimus.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "vferrickg@washington.edu",
                            FirstName = "Vallie",
                            LastName = "Ferrick"
                        },
                        new
                        {
                            Id = 18,
                            Avatar = "https://robohash.org/quaeessedistinctio.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "lgusneyh@homestead.com",
                            FirstName = "Lotti",
                            LastName = "Gusney"
                        },
                        new
                        {
                            Id = 19,
                            Avatar = "https://robohash.org/quisquilaborum.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "nandryseki@senate.gov",
                            FirstName = "Niki",
                            LastName = "Andrysek"
                        },
                        new
                        {
                            Id = 20,
                            Avatar = "https://robohash.org/rerumdoloresporro.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "rhansej@bbc.co.uk",
                            FirstName = "Renato",
                            LastName = "Hanse"
                        },
                        new
                        {
                            Id = 21,
                            Avatar = "https://robohash.org/quiautnatus.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "emazzillik@shop-pro.jp",
                            FirstName = "Elyssa",
                            LastName = "Mazzilli"
                        },
                        new
                        {
                            Id = 22,
                            Avatar = "https://robohash.org/excepturidebitisaliquid.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "btuttiettl@goo.gl",
                            FirstName = "Brinn",
                            LastName = "Tuttiett"
                        },
                        new
                        {
                            Id = 23,
                            Avatar = "https://robohash.org/delectusinventoreomnis.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "mconaghym@va.gov",
                            FirstName = "Maxy",
                            LastName = "Conaghy"
                        },
                        new
                        {
                            Id = 24,
                            Avatar = "https://robohash.org/aperiamquibusdamodio.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "vcamposn@ibm.com",
                            FirstName = "Valery",
                            LastName = "Campos"
                        },
                        new
                        {
                            Id = 25,
                            Avatar = "https://robohash.org/nonconsequaturtotam.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "ascarbarrowo@state.tx.us",
                            FirstName = "Alphonso",
                            LastName = "Scarbarrow"
                        },
                        new
                        {
                            Id = 26,
                            Avatar = "https://robohash.org/utautminima.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "cburstowp@foxnews.com",
                            FirstName = "Corey",
                            LastName = "Burstow"
                        },
                        new
                        {
                            Id = 27,
                            Avatar = "https://robohash.org/iureexanimi.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "agirodinq@mlb.com",
                            FirstName = "Adrian",
                            LastName = "Girodin"
                        },
                        new
                        {
                            Id = 28,
                            Avatar = "https://robohash.org/doloresimiliquedolores.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "acabralesr@google.co.uk",
                            FirstName = "Aubrie",
                            LastName = "Cabrales"
                        },
                        new
                        {
                            Id = 29,
                            Avatar = "https://robohash.org/quaspariaturmolestias.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "bdymotts@sakura.ne.jp",
                            FirstName = "Benjy",
                            LastName = "Dymott"
                        },
                        new
                        {
                            Id = 30,
                            Avatar = "https://robohash.org/accusantiumetat.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "dmacartet@sciencedaily.com",
                            FirstName = "Danya",
                            LastName = "MacArte"
                        },
                        new
                        {
                            Id = 31,
                            Avatar = "https://robohash.org/nesciuntnonrepellendus.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "dmarzelou@tmall.com",
                            FirstName = "Dion",
                            LastName = "Marzelo"
                        },
                        new
                        {
                            Id = 32,
                            Avatar = "https://robohash.org/sapientequasvoluptatibus.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "fthreshv@senate.gov",
                            FirstName = "Finley",
                            LastName = "Thresh"
                        },
                        new
                        {
                            Id = 33,
                            Avatar = "https://robohash.org/doloresdelectusveniam.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "pstillmanw@issuu.com",
                            FirstName = "Pamela",
                            LastName = "Stillman"
                        },
                        new
                        {
                            Id = 34,
                            Avatar = "https://robohash.org/commodisedconsequatur.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "sgatlinx@senate.gov",
                            FirstName = "Sharline",
                            LastName = "Gatlin"
                        },
                        new
                        {
                            Id = 35,
                            Avatar = "https://robohash.org/sedlaboreblanditiis.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "bburwelly@privacy.gov.au",
                            FirstName = "Barnebas",
                            LastName = "Burwell"
                        },
                        new
                        {
                            Id = 36,
                            Avatar = "https://robohash.org/expeditaaliasquia.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "jharkesz@facebook.com",
                            FirstName = "Janette",
                            LastName = "Harkes"
                        },
                        new
                        {
                            Id = 37,
                            Avatar = "https://robohash.org/totamvelquos.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "croach10@networkadvertising.org",
                            FirstName = "Clarance",
                            LastName = "Roach"
                        },
                        new
                        {
                            Id = 38,
                            Avatar = "https://robohash.org/repellatdoloremipsa.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "lbayne11@paypal.com",
                            FirstName = "Lauren",
                            LastName = "Bayne"
                        },
                        new
                        {
                            Id = 39,
                            Avatar = "https://robohash.org/quosdoloreasperiores.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "estealy12@discovery.com",
                            FirstName = "Ethan",
                            LastName = "Stealy"
                        },
                        new
                        {
                            Id = 40,
                            Avatar = "https://robohash.org/possimusquiaid.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "dshillabeare13@washingtonpost.com",
                            FirstName = "Deb",
                            LastName = "Shillabeare"
                        },
                        new
                        {
                            Id = 41,
                            Avatar = "https://robohash.org/officiautfuga.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "challbord14@tamu.edu",
                            FirstName = "Camilla",
                            LastName = "Hallbord"
                        },
                        new
                        {
                            Id = 42,
                            Avatar = "https://robohash.org/minimaconsequaturnihil.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "ocrackel15@sun.com",
                            FirstName = "Opaline",
                            LastName = "Crackel"
                        },
                        new
                        {
                            Id = 43,
                            Avatar = "https://robohash.org/maximelaboremolestias.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "llackie16@thetimes.co.uk",
                            FirstName = "Lorna",
                            LastName = "Lackie"
                        },
                        new
                        {
                            Id = 44,
                            Avatar = "https://robohash.org/quiarerumsaepe.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "mguillou17@state.gov",
                            FirstName = "Maggy",
                            LastName = "Guillou"
                        },
                        new
                        {
                            Id = 45,
                            Avatar = "https://robohash.org/errornumquamdistinctio.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "lconigsby18@sitemeter.com",
                            FirstName = "Lucien",
                            LastName = "Conigsby"
                        },
                        new
                        {
                            Id = 46,
                            Avatar = "https://robohash.org/consequaturofficiisrem.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "cmathelin19@howstuffworks.com",
                            FirstName = "Chicky",
                            LastName = "Mathelin"
                        },
                        new
                        {
                            Id = 47,
                            Avatar = "https://robohash.org/quieavelit.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "mcraft1a@utexas.edu",
                            FirstName = "Marisa",
                            LastName = "Craft"
                        },
                        new
                        {
                            Id = 48,
                            Avatar = "https://robohash.org/architectofugitet.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "agennrich1b@paypal.com",
                            FirstName = "Allister",
                            LastName = "Gennrich"
                        },
                        new
                        {
                            Id = 49,
                            Avatar = "https://robohash.org/consequatursitplaceat.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "hhammerton1c@taobao.com",
                            FirstName = "Halimeda",
                            LastName = "Hammerton"
                        },
                        new
                        {
                            Id = 50,
                            Avatar = "https://robohash.org/culparepellatincidunt.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "bcrosen1d@dell.com",
                            FirstName = "Bessy",
                            LastName = "Crosen"
                        },
                        new
                        {
                            Id = 51,
                            Avatar = "https://robohash.org/voluptatemquisquamofficia.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "ymacdermott1e@mit.edu",
                            FirstName = "Yvonne",
                            LastName = "MacDermott"
                        },
                        new
                        {
                            Id = 52,
                            Avatar = "https://robohash.org/cupiditatesintharum.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "nleppingwell1f@ca.gov",
                            FirstName = "Noell",
                            LastName = "Leppingwell"
                        },
                        new
                        {
                            Id = 53,
                            Avatar = "https://robohash.org/modilaborumqui.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "gstanyer1g@macromedia.com",
                            FirstName = "Gillan",
                            LastName = "Stanyer"
                        },
                        new
                        {
                            Id = 54,
                            Avatar = "https://robohash.org/autetdolores.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "gbullan1h@a8.net",
                            FirstName = "Gerrilee",
                            LastName = "Bullan"
                        },
                        new
                        {
                            Id = 55,
                            Avatar = "https://robohash.org/quaeratomnisquo.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "tklulicek1i@prlog.org",
                            FirstName = "Tate",
                            LastName = "Klulicek"
                        },
                        new
                        {
                            Id = 56,
                            Avatar = "https://robohash.org/optioofficiissit.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "msell1j@unblog.fr",
                            FirstName = "Myrvyn",
                            LastName = "Sell"
                        },
                        new
                        {
                            Id = 57,
                            Avatar = "https://robohash.org/providentconsequunturofficiis.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "cjanic1k@about.com",
                            FirstName = "Charisse",
                            LastName = "Janic"
                        },
                        new
                        {
                            Id = 58,
                            Avatar = "https://robohash.org/rerumculpaeum.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "gmullender1l@seesaa.net",
                            FirstName = "Gerrard",
                            LastName = "Mullender"
                        },
                        new
                        {
                            Id = 59,
                            Avatar = "https://robohash.org/hicveritatiseligendi.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "olowndsbrough1m@skyrock.com",
                            FirstName = "Orelle",
                            LastName = "Lowndsbrough"
                        },
                        new
                        {
                            Id = 60,
                            Avatar = "https://robohash.org/omnisadipisciiusto.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "abrizell1n@ucla.edu",
                            FirstName = "Alida",
                            LastName = "Brizell"
                        },
                        new
                        {
                            Id = 61,
                            Avatar = "https://robohash.org/autexcepturiamet.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "rpryer1o@hibu.com",
                            FirstName = "Rosie",
                            LastName = "Pryer"
                        },
                        new
                        {
                            Id = 62,
                            Avatar = "https://robohash.org/suscipitasperioresfacilis.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "josborn1p@nih.gov",
                            FirstName = "Julianne",
                            LastName = "Osborn"
                        },
                        new
                        {
                            Id = 63,
                            Avatar = "https://robohash.org/ipsamestlibero.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "sjoiner1q@zimbio.com",
                            FirstName = "Selle",
                            LastName = "Joiner"
                        },
                        new
                        {
                            Id = 64,
                            Avatar = "https://robohash.org/voluptateautmollitia.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "arojel1r@infoseek.co.jp",
                            FirstName = "Ashton",
                            LastName = "Rojel"
                        },
                        new
                        {
                            Id = 65,
                            Avatar = "https://robohash.org/asperioresilloexplicabo.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "aspeechley1s@ezinearticles.com",
                            FirstName = "Adelaida",
                            LastName = "Speechley"
                        },
                        new
                        {
                            Id = 66,
                            Avatar = "https://robohash.org/inciduntnatusest.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "apixton1t@lulu.com",
                            FirstName = "Ariadne",
                            LastName = "Pixton"
                        },
                        new
                        {
                            Id = 67,
                            Avatar = "https://robohash.org/temporeliberoeum.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "sjuly1u@wisc.edu",
                            FirstName = "Sigismondo",
                            LastName = "July"
                        },
                        new
                        {
                            Id = 68,
                            Avatar = "https://robohash.org/quiveniamiusto.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "pcrennan1v@webs.com",
                            FirstName = "Perry",
                            LastName = "Crennan"
                        },
                        new
                        {
                            Id = 69,
                            Avatar = "https://robohash.org/debitisetin.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "msiberry1w@gizmodo.com",
                            FirstName = "Marijo",
                            LastName = "Siberry"
                        },
                        new
                        {
                            Id = 70,
                            Avatar = "https://robohash.org/quisplaceataut.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "rbenka1x@networkadvertising.org",
                            FirstName = "Ron",
                            LastName = "Benka"
                        },
                        new
                        {
                            Id = 71,
                            Avatar = "https://robohash.org/perspiciatisliberonumquam.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "gpark1y@disqus.com",
                            FirstName = "Guinevere",
                            LastName = "Park"
                        },
                        new
                        {
                            Id = 72,
                            Avatar = "https://robohash.org/hicquasiet.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "asambedge1z@ca.gov",
                            FirstName = "Aurelia",
                            LastName = "Sambedge"
                        },
                        new
                        {
                            Id = 73,
                            Avatar = "https://robohash.org/temporibusmollitiaeligendi.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "btrapp20@constantcontact.com",
                            FirstName = "Barclay",
                            LastName = "Trapp"
                        },
                        new
                        {
                            Id = 74,
                            Avatar = "https://robohash.org/facilisestest.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "sseeley21@chron.com",
                            FirstName = "Sari",
                            LastName = "Seeley"
                        },
                        new
                        {
                            Id = 75,
                            Avatar = "https://robohash.org/doloresexillum.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "bwoolstenholmes22@tmall.com",
                            FirstName = "Brod",
                            LastName = "Woolstenholmes"
                        },
                        new
                        {
                            Id = 76,
                            Avatar = "https://robohash.org/autemeumaut.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "tbiddwell23@dyndns.org",
                            FirstName = "Torry",
                            LastName = "Biddwell"
                        },
                        new
                        {
                            Id = 77,
                            Avatar = "https://robohash.org/estnihilpraesentium.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "xcapelow24@cbslocal.com",
                            FirstName = "Xever",
                            LastName = "Capelow"
                        },
                        new
                        {
                            Id = 78,
                            Avatar = "https://robohash.org/accusamusutconsequuntur.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "bdunsford25@amazon.com",
                            FirstName = "Bab",
                            LastName = "Dunsford"
                        },
                        new
                        {
                            Id = 79,
                            Avatar = "https://robohash.org/ullamerroraccusamus.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "dgrishinov26@prweb.com",
                            FirstName = "Dre",
                            LastName = "Grishinov"
                        },
                        new
                        {
                            Id = 80,
                            Avatar = "https://robohash.org/estharumtempora.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "nblues27@slashdot.org",
                            FirstName = "Nobie",
                            LastName = "Blues"
                        },
                        new
                        {
                            Id = 81,
                            Avatar = "https://robohash.org/idinciduntconsequuntur.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "celphick28@state.gov",
                            FirstName = "Conrad",
                            LastName = "Elphick"
                        },
                        new
                        {
                            Id = 82,
                            Avatar = "https://robohash.org/atquedelenitiin.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "hthumnel29@cbc.ca",
                            FirstName = "Hurley",
                            LastName = "Thumnel"
                        },
                        new
                        {
                            Id = 83,
                            Avatar = "https://robohash.org/solutaillopraesentium.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "bbraisted2a@ihg.com",
                            FirstName = "Bunny",
                            LastName = "Braisted"
                        },
                        new
                        {
                            Id = 84,
                            Avatar = "https://robohash.org/sederrortotam.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "lrentoul2b@addtoany.com",
                            FirstName = "Lee",
                            LastName = "Rentoul"
                        },
                        new
                        {
                            Id = 85,
                            Avatar = "https://robohash.org/doloremitaqueeum.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "fwealthall2c@spotify.com",
                            FirstName = "Falito",
                            LastName = "Wealthall"
                        },
                        new
                        {
                            Id = 86,
                            Avatar = "https://robohash.org/sedverout.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "lscoines2d@prlog.org",
                            FirstName = "Libbi",
                            LastName = "Scoines"
                        },
                        new
                        {
                            Id = 87,
                            Avatar = "https://robohash.org/mollitiaquidemunde.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "dlilford2e@smh.com.au",
                            FirstName = "Damien",
                            LastName = "Lilford"
                        },
                        new
                        {
                            Id = 88,
                            Avatar = "https://robohash.org/temporibussedad.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "fbeig2f@symantec.com",
                            FirstName = "Far",
                            LastName = "Beig"
                        },
                        new
                        {
                            Id = 89,
                            Avatar = "https://robohash.org/voluptatemducimussed.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "jpetchey2g@blogtalkradio.com",
                            FirstName = "Jenifer",
                            LastName = "Petchey"
                        },
                        new
                        {
                            Id = 90,
                            Avatar = "https://robohash.org/etnoncorrupti.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "fcinnamond2h@scientificamerican.com",
                            FirstName = "Freedman",
                            LastName = "Cinnamond"
                        },
                        new
                        {
                            Id = 91,
                            Avatar = "https://robohash.org/facilisquamquisquam.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "carnaudet2i@springer.com",
                            FirstName = "Claudette",
                            LastName = "Arnaudet"
                        },
                        new
                        {
                            Id = 92,
                            Avatar = "https://robohash.org/eiusrepudiandaedelectus.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "mmcmurrugh2j@shareasale.com",
                            FirstName = "Monte",
                            LastName = "McMurrugh"
                        },
                        new
                        {
                            Id = 93,
                            Avatar = "https://robohash.org/minimaquiet.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "bsemmens2k@google.com.hk",
                            FirstName = "Brinna",
                            LastName = "Semmens"
                        },
                        new
                        {
                            Id = 94,
                            Avatar = "https://robohash.org/asperioresperspiciatisqui.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "fzecchinelli2l@netvibes.com",
                            FirstName = "Freddy",
                            LastName = "Zecchinelli"
                        },
                        new
                        {
                            Id = 95,
                            Avatar = "https://robohash.org/consequaturvelitmaiores.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "rtowner2m@nydailynews.com",
                            FirstName = "Ronny",
                            LastName = "Towner"
                        },
                        new
                        {
                            Id = 96,
                            Avatar = "https://robohash.org/itaqueautemconsectetur.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "mcusick2n@usatoday.com",
                            FirstName = "Mindy",
                            LastName = "Cusick"
                        },
                        new
                        {
                            Id = 97,
                            Avatar = "https://robohash.org/molestiaenequedicta.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "dgudahy2o@admin.ch",
                            FirstName = "Danielle",
                            LastName = "Gudahy"
                        },
                        new
                        {
                            Id = 98,
                            Avatar = "https://robohash.org/minusnihilunde.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "cwimpress2p@biblegateway.com",
                            FirstName = "Clare",
                            LastName = "Wimpress"
                        },
                        new
                        {
                            Id = 99,
                            Avatar = "https://robohash.org/recusandaeeteos.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "chegerty2q@hugedomains.com",
                            FirstName = "Chiquia",
                            LastName = "Hegerty"
                        },
                        new
                        {
                            Id = 100,
                            Avatar = "https://robohash.org/etconsecteturminus.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "scoombes2r@pcworld.com",
                            FirstName = "Sashenka",
                            LastName = "Coombes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
